### ISSUE TITLE
自動開 hackfoldr

### ISSUE THREAD

**Issue by hlb** [g0v/OneButton#4]
需求在 [hackpad](https://g0v.hackpad.com/%25E7%25AC%25AC%25E5%25A3%25B9%25E6%25AC%25A1%25E5%259F%25BA%25E7%25A4%258E%25E6%259D%25BE#-2016612)

**Comment by hlb** [comment]
我不會用 hackfolder （兩手一攤）

**Comment by hlb** [comment]
@yhsiang 我也不會 ethercalc （攤手）

**Comment by caasi** [comment]
認領認領 XDD
